nombres_buenos = [
        "ALCIVAR CEDEÑO JEREMY JARETH",
        "ANGULO CHEME DARKIEL FABRICIO",
        "ANZULEZ LOOR ISIS HAIDEE",
        "BASTIDAS MORILLO JASIEL SEGUNDO",
        "CASTAÑEDA CAGUA KALED YADIEL",
        "CEVALLOS RESTREPO MARIA VICTORIA",
        "CHUCURI OCHOA LIAM JABDIEL",
        "CRIOLLO CARRIEL DOMENICA JOSDANNY",
        "LOOR MEDRANDA ROY MATEO",
        "MEJIA MANZABA MILLIAM EZEQUIEL",
        "NAPA VILELA ISAAC JARED",
        "NEVAREZ MENENDEZ KEISHY ADRIANA",
        "ROSADO PRECIADO ISAAC DARELL",
        "SOLORZANO MELENDREZ JOSTIN RAFAEL",
        "VERA MONCAYO REBECA JUDITH",
        "VERA PACHECO MARIA SALOME"
    ]
nombres_malos = [
        "BERMEO CELORIO ALONDRA ABIGAIL",
        "CHEME LOPEZ ELIF FERNANDA",
        "DELGADO BURGA ANTONELLA SARAY",
        "LOOR MURILLO DYLAN SEBASTIÁN"
    ]